name: Update requirements.txt on PR

on:
  pull_request:
    paths:
      - "poetry.lock"

permissions:
  contents: write

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    env:
      POETRY_VERSION: 2.1.1
      POETRY_HOME: $HOME/.local/bin
      POETRY_NO_INTERACTION: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          pipx install poetry
          pipx inject poetry poetry-plugin-export
          poetry config virtualenvs.in-project true

      - name: Export requirements.txt
        if: env.changes != ''
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry export -f requirements.txt --output requirements.txt

      - name: Commit and push changes
        if: env.changes != ''
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git pull
          git add requirements.txt
          git commit -m "build(pip): update requirements.txt based on changes in poetry.lock"
          git push
